development:
  secret_key_base: f9dd205060d79da95acbdfa1115f2f53f4ed5032a94f8d3a47815725488248757ca0fff883ecceffd0b8f664e288878e9dedf5d6de3b8e0aa23f828b20417769
  github_app_secret: <%= ENV['GITHUB_APP_SECRET'] %>

test:
  secret_key_base: ad6a757fdf3839299a1236e3b99026f90b2b4bbc4578a4e3129b599bb7fecdcc53cae7b2cbf17eed3b78341b1d57b05efa8e7ddd38c1c82edb7914ed773e2ef8
  github_app_secret: <%= ENV['GITHUB_APP_SECRET'] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_app_id: <%= ENV["GITHUB_APP_ID"] %>
  github_app_secret: <%= ENV["GITHUB_APP_SECRET"] %>
